<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <RootNamespace>FullThrust.Sim.Tests</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System" />
    <ProjectReference Include="../sim/FullThrust.Sim.csproj" />
  </ItemGroup>

</Project>
